server:
  port: 8081

spring:
  application:
    name: dataset-service

  # --- Cấu hình kết nối ---
  data:
    # MongoDB
    mongodb:
      uri: mongodb://admin:password@mongo-db:27017/openlinkedhub_db?authSource=admin
    # Redis
    redis:
      host: redis
      port: 6379

  # Kafka
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: dataset-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  # --- Cấu hình GraphQL ---
  graphql:
    graphiql:
      enabled: true
    schema:
      locations: classpath:graphql/
      printer:
        enabled: true