services:
  auth-db:
    image: postgres:16
    container_name: openlinkedhub-auth-postgres
    ports: ["5433:5432"]
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
      POSTGRES_DB: auth_db
    networks: [openlinkedhub-backend-net]
    volumes: [auth-db-data:/var/lib/postgresql/data]

  redis:
    image: redis:7.2-alpine
    container_name: openlinkedhub-redis
    ports: ["6379:6379"]
    networks: [openlinkedhub-backend-net]

networks:
  openlinkedhub-backend-net:
    driver: bridge

volumes:
  auth-db-data: