server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # 1. Route cho Auth Service
        - id: auth-service-route
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**

        # 2. Route cho Dataset Service
        - id: dataset-service-route
          uri: lb://dataset-service
          predicates:
            - Path=/graphql/**
